# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }', position: ' { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel'', position: ' city: cities.first)
User.destroy_all
Userplayer.destroy_all
Usergame.destroy_all
Player.destroy_all
Player.create(name:'Alasdair Dickinson', position: 'Loosehead Prop')
Player.create(name:'Cian Healy', position: 'Loosehead Prop')
Player.create(name:'Gethin Jenkins', position: 'Loosehead Prop')
Player.create(name:'Jack McGrath', position: 'Loosehead Prop')
Player.create(name:'Joe Marler', position: 'Loosehead Prop')
Player.create(name:'Mako Vunipola', position: 'Loosehead Prop')
Player.create(name:'Nicky Smith', position: 'Loosehead Prop')
Player.create(name:'Alan Dell', position: 'Loosehead Prop')
Player.create(name:'Rob Evans', position: 'Loosehead Prop')
Player.create(name:'Dan Cole', position: 'Loosehead Prop')
Player.create(name:'Tadhg Furlong', position: 'Tighthead Prop')
Player.create(name:'WP Nel', position: 'Tighthead Prop')
Player.create(name:'Kyle Sinckler', position: 'Tighthead Prop')
Player.create(name:'Finlay Bealham', position: 'Tighthead Prop')
Player.create(name:'Samson Lee', position: 'Tighthead Prop')
Player.create(name:'Thomas Francis', position: 'Tighthead Prop')
Player.create(name:'Zander Fagerson', position: 'Tighthead Prop')
Player.create(name:'Dylan Hartley', position: 'Hooker')
Player.create(name:'Jamie George', position: 'Hooker')
Player.create(name:'Rory Best', position: 'Hooker')
Player.create(name:'Ken Owens', position: 'Hooker')
Player.create(name:'Tommy Taylor', position: 'Hooker')
Player.create(name:'Sean Cronin', position: 'Hooker')
Player.create(name:'Ross Ford', position: 'Hooker')
Player.create(name:'Fraser Brown', position: 'Hooker')
Player.create(name:'Donnacha Ryan', position: 'Second Row')
Player.create(name:'Devin Toner', position: 'Second Row')
Player.create(name:'Iain Henderson', position: 'Second Row')
Player.create(name:'Ultan Dillane', position: 'Second Row')
Player.create(name:'Maro Itoje', position: 'Second Row')
Player.create(name:'George Kruis', position: 'Second Row')
Player.create(name:'Joe Launchbury', position: 'Second Row')
Player.create(name:'Courtney Lawes', position: 'Second Row')
Player.create(name:'Alun Wyn Jones', position: 'Second Row')
Player.create(name:'Luke Charteris', position: 'Second Row')
Player.create(name:'Jonny Gray', position: 'Second Row')
Player.create(name:'Richie Gray', position: 'Second Row')
Player.create(name:'CJ Stander', position: 'Blindeside Flanker')
Player.create(name:'Josh Van Der Flier', position: 'Blindeside Flanker')
Player.create(name:'Peter O Mahony', position: 'Blindeside Flanker')
Player.create(name:'Chris Robshaw', position: 'Blindeside Flanker')
Player.create(name:'Tom Wood', position: 'Blindeside Flanker')
Player.create(name:'Ross Moriarty', position: 'Blindeside Flanker')
Player.create(name:'John Barclay', position: 'Blindeside Flanker')
Player.create(name:'Robert Harley', position: 'Blindeside Flanker')
Player.create(name:'Billy Vunipola', position: 'Number 8')
Player.create(name:'Nathan Hughes', position: 'Number 8')
Player.create(name:'Jamie Heaslip', position: 'Number 8')
Player.create(name:'Taulupe Faletau', position: 'Number 8')
Player.create(name:'Ryan Wilson', position: 'Number 8')
Player.create(name:'Sean OBrien', position: 'Openside Flanker')
Player.create(name:'James Haskell', position: 'Openside Flanker')
Player.create(name:'Jack Clifford', position: 'Openside Flanker')
Player.create(name:'Teimana Harrison', position: 'Openside Flanker')
Player.create(name:'Sam Warburton', position: 'Openside Flanker')
Player.create(name:'Justin Tipuric', position: 'Openside Flanker')
Player.create(name:'Hamish Watson', position: 'Openside Flanker')
Player.create(name:'John Hardie', position: 'Openside Flanker')
Player.create(name:'Conor Murray', position: 'Scrum Half')
Player.create(name:'Ben Youngs', position: 'Scrum Half')
Player.create(name:'Danny Care', position: 'Scrum Half')
Player.create(name:'Rhys Webb', position: 'Scrum Half')
Player.create(name:'Gareth Davies', position: 'Scrum Half')
Player.create(name:'Greig Laidlaw', position: 'Scrum Half')
Player.create(name:'Johnny Sexton', position: 'Outside Half')
Player.create(name:'Paddy Jackson', position: 'Outside Half')
Player.create(name:'George Ford', position: 'Outside Half')
Player.create(name:'Dan Biggar', position: 'Outside Half')
Player.create(name:'Sam Davies', position: 'Outside Half')
Player.create(name:'Finn Russell', position: 'Outside Half')
Player.create(name:'Robbie Henshaw', position: 'Inside Centre')
Player.create(name:'Ben Teo', position: 'Inside Centre')
Player.create(name:'Jamie Roberts', position: 'Inside Centre')
Player.create(name:'Scott Williams', position: 'Inside Centre')
Player.create(name:'Alex Dunbar', position: 'Inside Centre')
Player.create(name:'Duncan Taylor', position: 'Inside Centre')
Player.create(name:'Matt Scott', position: 'Inside Centre')
Player.create(name:'Super Gavin Henson', position: 'Inside Centre')
Player.create(name:'Jared Payne', position: 'Outside Centre')
Player.create(name:'Garry Ringrose', position: 'Outside Centre')
Player.create(name:'Luke Marshall', position: 'Outside Centre')
Player.create(name:'Jonathan Joseph', position: 'Outside Centre')
Player.create(name:'Henry Slade', position: 'Outside Centre')
Player.create(name:'Elliot Daly', position: 'Outside Centre')
Player.create(name:'Jonathan Davies', position: 'Outside Centre')
Player.create(name:'Keith Earls', position: 'Wings')
Player.create(name:'Craig Gilroy', position: 'Wings')
Player.create(name:'Andrew Trimble', position: 'Wings')
Player.create(name:'Tommy Bowe', position: 'Wings')
Player.create(name:'Tommy Seymour', position: 'Wings')
Player.create(name:'Tim Visser', position: 'Wings')
Player.create(name:'Sean Maitland', position: 'Wings')
Player.create(name:'Jack Nowell', position: 'Wings')
Player.create(name:'Jonny May', position: 'Wings')
Player.create(name:'Anthony Watson', position: 'Wings')
Player.create(name:'Semesa Rokoduguni', position: 'Wings')
Player.create(name:'Chris Ashton', position: 'Wings')
Player.create(name:'Christian Wade', position: 'Wings')
Player.create(name:'Marland Yarde', position: 'Wings')
Player.create(name:'Denny Solomona', position: 'Wings')
Player.create(name:'George North', position: 'Wings')
Player.create(name:'Keelan Giles', position: 'Wings')
Player.create(name:'Rob Kearney', position: 'Fullback' )
Player.create(name:'Simon Zebo', position: 'Fullback')
Player.create(name:'Tiernan O Halloran', position: 'Fullback' )
Player.create(name:'Mike Brown', position: 'Fullback')
Player.create(name:'Alex Goode', position: 'Fullback')
Player.create(name:'Leigh Halfpenny', position: 'Fullback')
Player.create(name:'Liam Williams', position: 'Fullback' )
Player.create(name:'Stuart Hogg', position: 'Fullback')
Game.destroy_all
Game.create(game_date:'03-06-2017', ref:1, home_team:'Provincial Union Team', away_team:'Lions', location:'Toll Stadium Whangarei')
Game.create(game_date:'07-06-2017', ref:2, home_team:'Blues', away_team:'Lions', location:'Eden Park Auckland')
Game.create(game_date:'10-06-2017', ref:3, home_team:'Crusaders', away_team:'Lions', location:'AMI Stadium Christchurch')
Game.create(game_date:'13-06-2017', ref:4, home_team:'Highlanders', away_team:'Lions', location:'Forsyth Barr Stadium Dunedin')
Game.create(game_date:'17-06-2017', ref:5, home_team:'Maori All Blacks', away_team:'Lions', location:'Rotorua International Stadium')
Game.create(game_date:'20-06-2017', ref:6, home_team:'Chiefs', away_team:'Lions', location:'FMG Stadium Waikato Hamilton')
Game.create(game_date:'24-06-2017', ref:7, home_team:'All Blacks', away_team:'Lions', location:'Eden Park Auckland')
Game.create(game_date:'27-06-2017', ref:8, home_team:'Hurricanes', away_team:'Lions', location:'Westpac Stadium Wellington')
Game.create(game_date:'01-07-2017', ref:9, home_team:'All Blacks', away_team:'Lions', location:'Westpac Stadium Wellington')
Game.create(game_date:'08-07-2017', ref:10, home_team:'All Blacks', away_team:'Lions', location:'Eden Park Auckland')